[package]
name = "macho"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@nexusguard.com>"]

[dependencies]
log = "0.3"
byteorder = "0.5"
uuid = "0.2"

[dev-dependencies]
env_logger = "0.3"

[lib]
name = "macho"
