[package]
name = "mach_object"
version = "0.1.2"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "Mach-O File Format Parser for Rust"
documentation = "http://flier.github.io/rust-macho/"
homepage = "http://flier.github.io/rust-macho/"
repository = "https://github.com/flier/rust-macho"
license = "Apache-2.0"

[dependencies]
log = "0.3"
libc = "0.2"
byteorder = "0.5"
uuid = "0.4"
time = "0.1"
bitflags = "0.5"
lazy_static = "0.1"

[dev-dependencies]
env_logger = "0.3"
diff = "0.1"
getopts = "0.2"
memmap = "0.3"

[lib]
name = "mach_object"

[[example]]
name = "otool"
path = "examples/otool.rs"
test = false
bench = false
